#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-wiremock
Version  : 2.19.0
Release  : 1
URL      : https://github.com/tomakehurst/wiremock/archive/2.19.0.tar.gz
Source0  : https://github.com/tomakehurst/wiremock/archive/2.19.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/2.19.0/wiremock-2.19.0.jar
Source2  : https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/2.19.0/wiremock-2.19.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: mvn-wiremock-data = %{version}-%{release}
Requires: mvn-wiremock-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
WireMock - a web service test double for all occasions
======================================================

%package data
Summary: data components for the mvn-wiremock package.
Group: Data

%description data
data components for the mvn-wiremock package.


%package license
Summary: license components for the mvn-wiremock package.
Group: Default

%description license
license components for the mvn-wiremock package.


%prep
%setup -q -n wiremock-2.19.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-wiremock
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-wiremock/LICENSE.txt
cp docs-v2/LICENSE %{buildroot}/usr/share/package-licenses/mvn-wiremock/docs-v2_LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/tomakehurst/wiremock/2.19.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/tomakehurst/wiremock/2.19.0/wiremock-2.19.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/tomakehurst/wiremock/2.19.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/tomakehurst/wiremock/2.19.0/wiremock-2.19.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/tomakehurst/wiremock/2.19.0/wiremock-2.19.0.jar
/usr/share/java/.m2/repository/com/github/tomakehurst/wiremock/2.19.0/wiremock-2.19.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-wiremock/LICENSE.txt
/usr/share/package-licenses/mvn-wiremock/docs-v2_LICENSE
